### PR TITLE
Record deployment on New Relic

### PR DESCRIPTION
**Pull request by AntoineAugusti**
I'm using the [REST API](https://rpm.newrelic.com/api/explore/application_deployments/create) to record deployments to New Relic, to have vertical lines on graphs when we deploy.

I can't add myself the `NEW_RELIC_API_KEY` secret to this repo but I can give you the key on Slack

### CODE REVIEW

**Comment by brdunfield** [comment]
Should the key be added to the staging LastPass instead?

**Comment by AntoineAugusti** [comment]
I'm not sure if we need it in LastPass as well. The key is not user-specific and can be seen multiple times on their UI.

But it should be on GitHub's UI because it'll be needed on GitHub Actions where HTTP requests will be made.

**Review by maxneuvians — APPROVED** [review]
LGTM

**Comment by AntoineAugusti** [comment]
@maxneuvians Added the secret but I'll wait next week to merge the PR

**Pull request merged**
